### ISSUE TITLE
Progress bar should use all horizontal space on screen

### ISSUE THREAD

**Issue by jacob-emery** [nenadstojanovikj/arch-beat#2]
Could you make the progress bar use all the available horizontal space before the user is brought to the display manager? Right now it uses only about a half of the horizontal space (and since it starts from left it is not even centred).

**Comment by nenad** [comment]
I wrote this 2y ago and not long after that I switched to `sway` and got rid of the plymouth splash screen. However, to answer your question, I'm not sure why you get such an issue. I just quickly peeked at the code and that's exactly how the dimensions of the loading bar are handled. You can check it out [here](https://github.com/nenad/arch-beat/blob/master/arch-beat.script#L17), where the X offset is set to 0 (left most of the screen) and [here](https://github.com/nenad/arch-beat/blob/master/arch-beat.script#L61) where the image is scaled according to the size given to plymouth from the [Window.GetWidth()](https://github.com/freedesktop/plymouth/blob/a588b3f7d16a3a8da56c6dbaf2429889375f4d3f/src/plugins/splash/script/script-lib-sprite.c#L201) function. As far as I can understand, the `GetWidth` function returns the size of the smallest resolution if you have multiple monitors attached. I wrote this script when I only used the laptop screen without external monitors, maybe in your case that's what's causing the trouble.

**Comment by jacob-emery** [comment]
Sorry if I reply only now. Your code seems correct also to me, however the loading bar sometimes is fully loaded, other times only less than 50%, other times only 75%, ... I don't really know why it does so.
However, it does not matter anymore, I changed your script a bit and I completely removed the loading bar (i also changed the logo 😜).

**Comment by nenad** [comment]
Ah, then I believe the problem is a little different than what you've originally described. I believe, if your computer boots fast, you won't ever see the progress bar going to 100%. I'm not sure how plymouth determines how much is loaded to be honest. However, I think I got good results with using [ShowDelay](https://wiki.archlinux.org/index.php/plymouth#Show_delay) when I was using it.

I'm glad that the script was useful to you :slightly_smiling_face:
